'use strict';
const KEY='kusa.workspace.v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const paths={folder:'M3 7h6l2-3h5l2 3h3v13H3z',chat:'M4 4h16v12H9l-5 4z',tasks:'M5 3h14v18H5z M8 11l3 3 5-6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',plus:'M12 5v14 M5 12h14',arrow:'M12 19V5 M5 12l7-7 7 7',chevron:'M9 5l7 7-7 7',down:'M5 9l7 7 7-7',file:'M5 3h9l5 5v13H5z M14 3v6h5 M8 13h8 M8 17h6',calendar:'M4 5h16v16H4z M4 10h16 M8 3v4 M16 3v4',close:'M6 6l12 12 M18 6L6 18',trash:'M4 6h16 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7 M14 10v7',edit:'M4 20l5-1L20 8l-5-5L4 14z M12 6l5 5',menu:'M4 6h16 M4 12h16 M4 18h16',help:'M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3 M12 18h.01',back:'M14 5l-7 7 7 7',download:'M12 3v12 M7 10l5 5 5-5 M4 17v4h16v-4'};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`;
const folder=mini=>`<span class="folder ${mini?'mini':''}" aria-hidden="true"></span>`;
const btn=(label,action,cls='',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${label}</button>`;
function seed(){return {version:1,demo:true,name:'Carl',model:'qwen2.5:3b',folders:[{id:'programming',name:'Programming'},{id:'history',name:'Philippine History'},{id:'math',name:'Mathematics'},{id:'general',name:'General'}],documents:[{id:uid(),folder:'programming',name:'Sample activity brief.txt',pages:[{number:1,text:'SAMPLE DOCUMENT — Demonstration only. Programming activity: Create a C++ program that reads two numbers and displays their sum. Submit your C++ source file, a screenshot of the output, and a short explanation of your solution. No submission deadline has been specified.'}]}],tasks:[{id:uid(),folder:'programming',title:'Complete the programming exercise',date:today(),time:'15:00',done:false},{id:uid(),folder:'history',title:'Write the history reflection',date:today(),time:'17:00',done:false},{id:uid(),folder:'math',title:'Finish the worksheet',date:today(),time:'20:00',done:false}],schedule:[{id:uid(),folder:'programming',title:'Programming',date:today(),start:'09:00',end:'10:30'},{id:uid(),folder:'history',title:'Philippine History',date:today(),start:'13:00',end:'14:30'}],chats:{}};}
let state;try{state=JSON.parse(localStorage.getItem(KEY))||seed();}catch{state=seed();}
let page='projects',tab='overview',activeFolder=null,chatFolder=state.folders[0]?.id||'',filter='open',busy=false,status=null;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('Storage is full. Export a backup and remove large files. Your last change is not saved.');return false;}}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
const findFolder=id=>state.folders.find(f=>f.id===id)?.name||'General';
function formatTime(t){if(!t)return 'Any time';const [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`;}
const folderOptions=selected=>state.folders.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?'selected':''}>${esc(f.name)}</option>`).join('');
function logo(){return '<span class="brand"><img src="assets/logo-transparent.png" alt="Kusa"></span>';}
function nav(){return `<nav class="nav" aria-label="Main navigation">${[['projects','folder','Projects'],['chat','k','Ask Kusa'],['tasks','tasks','Tasks'],['settings','settings','Settings']].map(([p,i,l])=>`<button data-action="nav" data-page="${p}" class="${page===p?'active':''}" ${page===p?'aria-current="page"':''}>${i==='k'?'<span class="k-icon">K</span>':icon(i)}<span>${l}</span></button>`).join('')}</nav>`;}
function header(){return `<header class="header">${logo()}<button class="avatar" data-action="nav" data-page="settings" aria-label="Open settings">${esc((state.name||'Me').slice(0,2).toUpperCase())}</button></header>`;}
let lastViewKey = null;
function render(){
 const viewKey = page + (page === "projects" ? ":" + tab + ":" + (activeFolder || "") : "");
 $('#app').innerHTML=page==='chat'?chatView():`<div class="shell">${header()}${page==='projects'?projectsView():page==='tasks'?tasksView():settingsView()}</div>${nav()}`;
 if(viewKey !== lastViewKey){ $('.shell').classList.add('page-enter'); lastViewKey = viewKey; }
 if(page==='chat'){$('.chat-body').scrollTop=$('.chat-body').scrollHeight;}
}
function tasksGroup(folderId,items){return `<details class="card subject" open><summary>${folder(true)}<strong>${esc(findFolder(folderId))}</strong><small>${items.filter(t=>t.done).length}/${items.length}</small>${icon('down')}</summary>${items.length?items.map(t=>`<div class="task-row ${t.done?'done':''}"><input type="checkbox" id="task-${t.id}" data-task="${t.id}" ${t.done?'checked':''} aria-label="Complete ${esc(t.title)}"><label for="task-${t.id}">${esc(t.title)}${t.date?`<small>${esc(t.date)}${t.time?' · '+formatTime(t.time):''}</small>`:''}</label><button class="icon-btn" data-action="edit-task" data-id="${t.id}" aria-label="Edit ${esc(t.title)}">${icon('edit')}</button></div>`).join(''):'<div class="empty">No tasks here yet.</div>'}</details>`;}
function projectsView(){return `<div class="heading"><div><h1>${activeFolder?esc(findFolder(activeFolder)):'My workspace'}</h1><p>${new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date())}</p></div>${activeFolder?btn(icon('back')+' Back','back-folders','small'):''}</div><div class="tabs" role="tablist">${['overview','documents','tasks'].map(t=>`<button role="tab" aria-selected="${tab===t}" data-action="tab" data-tab="${t}" class="${tab===t?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>${state.demo?'<div class="sample"><span>Sample workspace · replace with your own material</span><button data-action="clear-sample">Start fresh</button></div>':''}${tab==='overview'?overview():tab==='documents'?documentsView():tasksView(true)}`;}
function overview(){let due=state.tasks.filter(t=>t.date===today()&&!t.done).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'));let classes=state.schedule.filter(s=>s.date===today()).sort((a,b)=>a.start.localeCompare(b.start));return `<div class="workspace-grid"><section class="section"><div class="section-top"><h2>Today</h2>${btn(icon('plus')+' Schedule','add-schedule','small')}</div><div class="card today-card"><div class="today-sub"><div class="label">${icon('calendar')} Class schedule</div>${classes.length?classes.map(s=>`<div class="schedule-row"><span class="schedule-time">${formatTime(s.start)}<br>${formatTime(s.end)}</span><div class="schedule-content">${esc(s.title)}<small>${esc(findFolder(s.folder))}</small></div><button class="icon-btn" data-action="edit-schedule" data-id="${s.id}" aria-label="Edit ${esc(s.title)}">${icon('edit')}</button></div>`).join(''):'<p class="empty">A little breathing room. No classes scheduled today.</p>'}</div><div class="today-sub"><div class="label">${icon('file')} Due today <span class="badge">${due.length}</span></div><div class="timeline">${due.length?due.map(t=>`<div class="deadline"><time>${formatTime(t.time)}</time><div><button data-action="edit-task" data-id="${t.id}" style="padding:0;text-align:left">${esc(t.title)}</button><small>${esc(findFolder(t.folder))}</small></div></div>`).join(''):'<p class="empty">You’re clear for today. No pending deadlines.</p>'}</div></div></div></section><section class="section"><div class="section-top"><h2>Project materials</h2>${btn(icon('plus')+' Folder','add-folder','primary small')}</div>${folderGrid()}<p class="save-note">Your materials stay in this browser on this device.</p></section><section class="section"><div class="section-top"><h2>Preparation checklist</h2><button class="text-btn" data-action="add-task">+ Task</button></div>${state.folders.map(f=>tasksGroup(f.id,state.tasks.filter(t=>t.folder===f.id))).join('')}</section></div>`;}
function folderGrid(){return `<div class="folder-grid">${state.folders.map(f=>`<button class="card folder-card" data-action="open-folder" data-id="${esc(f.id)}">${folder(false)}<span><strong>${esc(f.name)}</strong><small>${state.documents.filter(d=>d.folder===f.id).length} files</small></span>${icon('chevron','chevron')}</button>`).join('')}</div>${!state.folders.length?'<div class="card empty">Create a subject folder to get started.</div>':''}`;}
function documentsView(){let docs=state.documents.filter(d=>!activeFolder||d.folder===activeFolder);return `<section class="section"><div class="file-actions">${btn(icon('plus')+' Add document','upload','primary')}${btn(icon('edit')+' Write a note','note')}${activeFolder?btn('Rename folder','rename-folder'):btn('New folder','add-folder')}</div>${!activeFolder?folderGrid():''}</section><section class="section"><div class="section-top"><h2>${activeFolder?'Folder contents':'All documents'}</h2><small>${docs.length} files</small></div><div class="card">${docs.length?docs.map(d=>`<div class="file-row"><span class="file-symbol">${icon('file')}</span><button class="file-open" data-action="view-doc" data-id="${d.id}"><strong>${esc(d.name)}</strong><small>${d.pages.length} ${d.name.toLowerCase().endsWith('.pdf')?'pages':'section(s)'} · ${esc(findFolder(d.folder))}</small></button><button class="icon-btn" data-action="move-doc" data-id="${d.id}" aria-label="Move ${esc(d.name)}">${icon('folder')}</button><button class="icon-btn" data-action="delete-doc" data-id="${d.id}" aria-label="Delete ${esc(d.name)}">${icon('trash')}</button></div>`).join(''):'<div class="empty">Add a PDF, TXT, or Markdown file, or write a note. Scanned PDFs aren’t supported yet.</div>'}</div></section>`;}
function tasksView(nested=false){let items=state.tasks.filter(t=>(!activeFolder||!nested||t.folder===activeFolder)&&(filter==='all'||(filter==='done'?t.done:!t.done)));return `${!nested?'<div class="heading"><div><h1>Your tasks</h1><p>A little progress, every day.</p></div>'+btn(icon('plus')+' Task','add-task','primary')+'</div>':'<div class="section-top"><h2>Subject checklists</h2>'+btn('+ Task','add-task','primary small')+'</div>'}<div class="task-filters">${[['open','To do'],['done','Completed'],['all','All']].map(([id,label])=>`<button data-action="filter" data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}</div>${state.folders.filter(f=>items.some(t=>t.folder===f.id)).map(f=>tasksGroup(f.id,items.filter(t=>t.folder===f.id))).join('')||'<div class="card empty">No tasks in this view.</div>'}`;}
function chatView(){const msgs=state.chats[chatFolder]||[];return `<div class="shell chat-shell"><header class="header"><button class="icon-btn" data-action="choose-folder" aria-label="Choose a subject folder">${icon('menu')}</button>${logo()}<button class="icon-btn" data-action="new-chat" aria-label="Start a new chat">${icon('edit')}</button></header><div class="scope"><select id="chat-folder" aria-label="Folder used for answers"><option value="" ${!chatFolder?'selected':''}>Choose a folder</option>${folderOptions(chatFolder)}</select></div><main class="chat-body" aria-label="Conversation">${msgs.length?msgs.map((m,i)=>messageHTML(m,i)).join(''):`<div class="chat-empty"><div class="hero-k" aria-hidden="true">K</div><h1>What can I help<br>you with?</h1><p>Ask about your notes and files.</p></div>`}${busy?'<div class="pending" role="status"><span class="dot"></span>Working with your local model…</div>':''}</main>${!msgs.length?'<div class="suggestions"><button data-action="suggest" data-prompt="Summarize the key points in my files.">'+icon('file')+'Summarize a file</button><button data-action="suggest" data-prompt="Explain the main concepts in my files in simple words.">'+icon('help')+'Explain a concept</button></div>':''}<form id="chat-form" class="composer"><button type="button" class="icon-btn" data-action="upload" aria-label="Attach a document">${icon('plus')}</button><textarea id="message" rows="1" aria-label="Message Kusa" placeholder="Message Kusa" maxlength="4000" ${busy?'disabled':''}></textarea><button class="send" aria-label="Send message" ${busy?'disabled':''}>${icon('arrow')}</button></form><p class="chat-help">Check important details against the sources.</p></div>${nav()}`;}
function messageHTML(m,i){return `<div class="bubble ${esc(m.role)} ${m.error?'error':''}">${esc(m.text)}${m.sources?.length?`<div class="sources">${m.sources.map((s,j)=>`<button class="source-btn" data-action="source" data-message="${i}" data-source="${j}">${esc(s.name)} · p. ${s.page}${s.cited?'':' · retrieved'}</button>`).join('')}</div>`:''}${m.tasks?.length?`<div>${btn('Review '+m.tasks.length+' tasks','review','',`data-message="${i}"`)}<small style="display:block">Review before adding to ${esc(findFolder(chatFolder))}.</small></div>`:''}</div>`;}
function settingsView(){return `<div class="settings"><div class="heading"><div><h1>Settings</h1><p>Make this space yours.</p></div></div><section class="card setting-block"><h2>Your workspace</h2><form id="profile-form"><label class="field">Your name<input name="name" value="${esc(state.name)}" maxlength="60" required></label><button class="btn primary">Save name</button></form></section><section class="card setting-block"><h2>Local AI connection</h2><p>Kusa connects to Ollama on this computer. Download a model once, then use it without internet. The phone-sized layout also works on your laptop.</p><div class="status" id="connection-status">${status?status.connected?`Ollama connected · ${status.models.length} local models`:'Ollama is not running. Open Ollama and check again.':'Connection not checked yet.'}</div><form id="model-form"><label class="field">Model name<input name="model" list="models" value="${esc(state.model)}" required maxlength="100"><datalist id="models">${(status?.models||[]).map(m=>`<option value="${esc(m)}">`).join('')}</datalist></label><div class="backup-actions"><button class="btn primary">Save model</button>${btn('Check connection','check')}</div></form><p style="margin-top:15px">Suggested starting model: <code>qwen2.5:3b</code>. Answers use selected excerpts, not necessarily every page. Always inspect the sources.</p></section><section class="card setting-block"><h2>Backup & portability</h2><p>Files, schedules, tasks, and chats are saved in this browser. Export regularly: clearing browser data removes them. Backups contain your document text.</p><div class="backup-actions">${btn(icon('download')+' Export backup','export')}${btn('Import backup','restore')}</div></section><section class="card setting-block"><h2>About this build</h2><p>Kusa v0.3 · Solo hackathon edition. PDF text extraction and AI inference run on your computer. No account, external fonts, analytics, or cloud AI calls. Voice, OCR, and cross-device sync are not included.</p>${state.demo?btn('Remove sample content','clear-sample','danger'):''}</section></div>`;}
function modal(title,body,onSubmit){$('#modal').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button class="icon-btn" data-action="close-modal" aria-label="Close">${icon('close')}</button></div>${body}`;$('#modal').showModal();if(onSubmit)$('#modal form').onsubmit=onSubmit;}
const actions=()=>`<div class="form-actions"><button type="button" class="btn" data-action="close-modal">Cancel</button><button class="btn primary">Save</button></div>`;
function taskForm(id){if(!state.folders.length)return toast('Create a folder first.');const task=state.tasks.find(t=>t.id===id)||{title:'',folder:activeFolder||chatFolder||state.folders[0].id,date:'',time:''};modal(id?'Edit task':'New task',`<form><label class="field">Task<input name="title" required maxlength="200" value="${esc(task.title)}"></label><label class="field">Subject<select name="folder">${folderOptions(task.folder)}</select></label><div class="form-grid"><label class="field">Due date (optional)<input type="date" name="date" value="${esc(task.date)}"></label><label class="field">Time (optional)<input type="time" name="time" value="${esc(task.time)}"></label></div>${id?btn('Delete task','delete-task','danger',`data-id="${id}"`):''}${actions()}</form>`,e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));if(v.time&&!v.date)return toast('Choose a date for this deadline.');if(id)Object.assign(task,v);else state.tasks.push({id:uid(),done:false,...v});persist();$('#modal').close();render();});}
function scheduleForm(id){if(!state.folders.length)return toast('Create a folder first.');const s=state.schedule.find(x=>x.id===id)||{title:'',folder:state.folders[0].id,date:today(),start:'09:00',end:'10:00'};modal(id?'Edit schedule':'Add to schedule',`<form><label class="field">Class or event<input name="title" value="${esc(s.title)}" required maxlength="100"></label><label class="field">Subject<select name="folder">${folderOptions(s.folder)}</select></label><label class="field">Date<input type="date" name="date" value="${esc(s.date)}" required></label><div class="form-grid"><label class="field">Starts<input name="start" type="time" value="${esc(s.start)}" required></label><label class="field">Ends<input name="end" type="time" value="${esc(s.end)}" required></label></div>${id?btn('Delete schedule entry','delete-schedule','danger',`data-id="${id}"`):''}${actions()}</form>`,e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(v.end<=v.start)return toast('End time must be after start time.');if(id)Object.assign(s,v);else state.schedule.push({id:uid(),...v});persist();$('#modal').close();render();});}
async function api(path,data){const response=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});let body;try{body=await response.json();}catch{throw Error('Start Kusa with start.bat and open http://localhost:8765.');}if(!response.ok)throw Error(body.error||'Request failed.');return body;}
async function send(question){if(busy||!question.trim())return;if(!chatFolder)return toast('Choose a subject folder first.');const target=chatFolder;const docs=state.documents.filter(d=>d.folder===target);if(!docs.length)return toast('Add a document or note to this folder first.');const history=[...(state.chats[target]||[])].filter(m=>!m.error);state.chats[target]=state.chats[target]||[];state.chats[target].push({role:'user',text:question.trim()});busy=true;persist();render();try{const result=await api('chat',{question,model:state.model,documents:docs,history:history.slice(-4)});state.chats[target].push({role:'assistant',text:result.answer,tasks:result.tasks,sources:result.sources.map(s=>({...s,cited:result.source_ids.includes(s.id)}))});}catch(e){state.chats[target].push({role:'assistant',text:e.message,error:true});}finally{busy=false;persist();render();}}
function validBackup(x){return x&&x.version===1&&Array.isArray(x.folders)&&x.folders.length<=100&&x.folders.every(f=>typeof f.id==='string'&&/^[a-zA-Z0-9-]+$/.test(f.id)&&typeof f.name==='string')&&['tasks','documents','schedule'].every(k=>Array.isArray(x[k])&&x[k].every(v=>typeof v.id==='string'&&/^[a-zA-Z0-9-]+$/.test(v.id)&&x.folders.some(f=>f.id===v.folder)))&&x.tasks.every(t=>typeof t.title==='string'&&typeof t.done==='boolean'&&typeof t.date==='string'&&typeof t.time==='string')&&x.schedule.every(s=>['title','date','start','end'].every(k=>typeof s[k]==='string'))&&x.documents.every(d=>typeof d.name==='string'&&Array.isArray(d.pages)&&d.pages.every(p=>typeof p.text==='string'&&Number.isInteger(p.number)))&&typeof x.name==='string'&&typeof x.model==='string';}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=el.dataset.id;
 if(a==='nav'){page=el.dataset.page;render();}
 if(a==='tab'){tab=el.dataset.tab;render();}
 if(a==='filter'){filter=el.dataset.filter;render();}
 if(a==='open-folder'){activeFolder=id;tab='documents';render();}
 if(a==='back-folders'){activeFolder=null;tab='overview';render();}
 if(a==='close-modal')$('#modal').close();
 if(a==='add-folder'||a==='rename-folder'){modal(a==='add-folder'?'New folder':'Rename folder',`<form><label class="field">Folder name<input name="name" required maxlength="70" value="${a==='rename-folder'?esc(findFolder(activeFolder)):''}" placeholder="e.g. Programming"></label>${actions()}</form>`,event=>{event.preventDefault();const name=new FormData(event.target).get('name').trim();if(!name)return;if(a==='rename-folder')state.folders.find(f=>f.id===activeFolder).name=name;else{const f={id:uid(),name};state.folders.push(f);if(!chatFolder)chatFolder=f.id;}persist();$('#modal').close();render();});}
 if(a==='add-task'||a==='edit-task')taskForm(id);
 if(a==='add-schedule'||a==='edit-schedule')scheduleForm(id);
 if(a==='delete-task'){state.tasks=state.tasks.filter(t=>t.id!==id);persist();$('#modal').close();render();}
 if(a==='delete-schedule'){state.schedule=state.schedule.filter(s=>s.id!==id);persist();$('#modal').close();render();}
 if(a==='upload'){if(!state.folders.length)return toast('Create a folder first.');modal('Add documents',`<form><p class="inline-help">Text-based PDF, TXT, or Markdown. Up to 10 MB per file; PDFs up to 100 pages.</p><label class="field">Save in folder<select name="folder">${folderOptions(page==='chat'?chatFolder:activeFolder||state.folders[0].id)}</select></label><div class="form-actions"><button class="btn primary">Choose files</button></div></form>`,event=>{event.preventDefault();$('#upload').dataset.folder=new FormData(event.target).get('folder');$('#modal').close();$('#upload').click();});}
 if(a==='note'){if(!state.folders.length)return toast('Create a folder first.');modal('Write a note',`<form><label class="field">Title<input name="title" required maxlength="100" placeholder="Meeting notes"></label><label class="field">Folder<select name="folder">${folderOptions(activeFolder||state.folders[0].id)}</select></label><label class="field">Your note<textarea name="text" required maxlength="30000" placeholder="Start writing…"></textarea></label>${actions()}</form>`,event=>{event.preventDefault();const v=Object.fromEntries(new FormData(event.target));state.documents.push({id:uid(),folder:v.folder,name:v.title+'.txt',pages:[{number:1,text:v.text}]});persist();$('#modal').close();render();});}
 if(a==='view-doc'){const d=state.documents.find(d=>d.id===id);modal(d.name,`<div class="source-text">${d.pages.map(p=>`<h3>Page ${p.number}</h3>${esc(p.text)}<hr>`).join('')}</div>`);}
 if(a==='move-doc'){const d=state.documents.find(d=>d.id===id);modal('Move document',`<form><label class="field">Folder<select name="folder">${folderOptions(d.folder)}</select></label>${actions()}</form>`,event=>{event.preventDefault();d.folder=new FormData(event.target).get('folder');persist();$('#modal').close();render();});}
 if(a==='delete-doc'){const d=state.documents.find(d=>d.id===id);modal('Delete document?',`<p class="inline-help">Remove ${esc(d.name)} from this workspace? Previous chat excerpts remain in chat history.</p><div class="form-actions">${btn('Cancel','close-modal')}${btn('Delete document','confirm-delete','danger',`data-id="${id}"`)}</div>`);}
 if(a==='confirm-delete'){state.documents=state.documents.filter(d=>d.id!==id);persist();$('#modal').close();render();}
 if(a==='suggest'){const input=$('#message');input.value=el.dataset.prompt;input.focus();}
 if(a==='choose-folder'){$('#chat-folder').focus();try{$('#chat-folder').showPicker();}catch{}}
 if(a==='new-chat'){if(busy)return toast('Wait for the current answer to finish.');modal('Start a new chat?',`<p class="inline-help">This clears the saved conversation for this folder. Documents and tasks are kept.</p><div class="form-actions">${btn('Cancel','close-modal')}${btn('Start new chat','confirm-new-chat','primary')}</div>`);}
 if(a==='confirm-new-chat'){state.chats[chatFolder]=[];persist();$('#modal').close();render();}
 if(a==='source'){const s=state.chats[chatFolder][+el.dataset.message].sources[+el.dataset.source];modal(s.name+' · page '+s.page,`<p class="inline-help">${s.cited?'Referenced by the model. Verify that this passage supports the answer.':'Retrieved context sent to the model; not explicitly cited in its answer.'}</p><div class="source-text">${esc(s.text)}</div>`);}
 if(a==='review'){const targetFolder=chatFolder;const m=state.chats[targetFolder][+el.dataset.message];modal('Review suggested tasks',`<form><p class="inline-help">Edit or uncheck items before saving. No deadline will be added automatically.</p><label class="field">Subject<select name="folder">${folderOptions(targetFolder)}</select></label>${m.tasks.map((t,i)=>`<div class="review-row"><input type="checkbox" name="include${i}" checked aria-label="Include task ${i+1}"><input name="task${i}" aria-label="Task ${i+1}" maxlength="200" value="${esc(t)}" required></div>`).join('')}${actions()}</form>`,event=>{event.preventDefault();const values=new FormData(event.target);let count=0;for(let i=0;i<m.tasks.length;i++){const title=values.get('task'+i).trim();if(values.has('include'+i)&&title&&!state.tasks.some(t=>t.folder===values.get('folder')&&t.title===title)){state.tasks.push({id:uid(),title,folder:values.get('folder'),done:false,date:'',time:''});count++;}}persist();$('#modal').close();toast(`${count} tasks saved.`);});}
 if(a==='check'){el.disabled=true;try{status=await api('status');}catch{status={connected:false,models:[]};}render();}
 if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='kusa-backup-'+today()+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(a==='restore')$('#restore').click();
 if(a==='clear-sample'){modal('Start with a clean workspace?',`<p class="inline-help">This removes ALL current documents, tasks, schedules, and chats, including anything you added. Export a backup first if needed. Subject folders are kept.</p><div class="form-actions">${btn('Cancel','close-modal')}${btn('Clear workspace','confirm-clear','danger')}</div>`);}
 if(a==='confirm-clear'){if(busy)return toast('Wait for the current answer to finish.');state.documents=[];state.tasks=[];state.schedule=[];state.chats={};state.demo=false;persist();$('#modal').close();render();}
});
document.addEventListener('change',e=>{if(e.target.dataset.task){const t=state.tasks.find(t=>t.id===e.target.dataset.task);t.done=e.target.checked;persist();render();}if(e.target.id==='chat-folder'){chatFolder=e.target.value;render();}});
document.addEventListener('submit',e=>{if(e.target.id==='chat-form'){e.preventDefault();send($('#message').value);}if(e.target.id==='profile-form'){e.preventDefault();state.name=new FormData(e.target).get('name').trim()||'Me';persist();render();toast('Name saved.');}if(e.target.id==='model-form'){e.preventDefault();state.model=new FormData(e.target).get('model').trim();persist();toast('Model saved.');}});
document.addEventListener('keydown',e=>{if(e.target.id==='message'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value);}});
$('#upload').addEventListener('change',async e=>{const target=e.target.dataset.folder;const files=[...e.target.files];for(const file of files){try{if(file.size>10000000)throw Error('Use files under 10 MB.');toast('Importing '+file.name+'…');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));const result=await api('extract',{name:file.name,data:btoa(binary)});const doc={id:uid(),folder:target,name:file.name,pages:result.pages};state.documents.push(doc);if(!persist()){state.documents.pop();throw Error('Not imported: browser storage is full. Export a backup and remove large files.');}toast(file.name+' imported.');}catch(error){toast(error.message);break;}}e.target.value='';render();});
$('#restore').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('Backup must be under 5 MB.');const candidate=JSON.parse(await file.text());if(!validBackup(candidate))throw Error('This is not a supported Kusa backup.');modal('Restore backup?',`<form><p class="inline-help">Replace this workspace with ${candidate.folders.length} folders and ${candidate.documents.length} documents? Export your current workspace first. Chat history is not imported in this version.</p><div class="form-actions"><button type="button" class="btn" data-action="close-modal">Cancel</button><button class="btn primary">Restore</button></div></form>`,event=>{event.preventDefault();if(busy)return toast('Wait for the current answer to finish.');const previous=state;state={...candidate,chats:{}};if(!persist()){state=previous;return;}activeFolder=null;chatFolder=state.folders[0]?.id||'';$('#modal').close();render();toast('Workspace restored.');});}catch(error){toast(error.message);}e.target.value='';});
render();persist();
